apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loadgen-wallet
  namespace: url-shortener-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: loadgen-wallet-secret
    creationPolicy: Owner
    template:
      data:
        WALLET_KEY_1: "{{ .wallet_key_1 }}"
        WALLET_KEY_2: "{{ .wallet_key_2 }}"
        WALLET_KEY_3: "{{ .wallet_key_3 }}"
  data:
    - secretKey: wallet_key_1
      remoteRef:
        key: load-test-wallet-key-1
    - secretKey: wallet_key_2
      remoteRef:
        key: load-test-wallet-key-2
    - secretKey: wallet_key_3
      remoteRef:
        key: load-test-wallet-key-3
