apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radius-signer
  namespace: url-shortener-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: radius-signer-secret
    creationPolicy: Owner
    template:
      data:
        RPC_URL: "{{ .radius_rpc_url }}"
        SERVICE_WALLET_ADDRESS: "{{ .service_wallet_address }}"
  data:
    - secretKey: radius_rpc_url
      remoteRef:
        key: radius-rpc-url-testnet
    - secretKey: service_wallet_address
      remoteRef:
        key: service-wallet-address-testnet
