---
# Source: url-shortener/templates/externalsecret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: url-shortener-prod-external-secret
  labels:
    helm.sh/chart: url-shortener-0.1.0
    app.kubernetes.io/name: url-shortener
    app.kubernetes.io/instance: url-shortener-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: url-shortener-prod-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgresql://urlshortener:{{ .database_password }}@url-shortener-prod-postgresql.url-shortener-prod.svc.cluster.local:5432/urlshortener"
        DATABASE_PASSWORD: "{{ .database_password }}"
        SERVICE_WALLET_ADDRESS: "{{ .service_wallet_address }}"
  data:
    - secretKey: database_password
      remoteRef:
        key: database-password
    - secretKey: service_wallet_address
      remoteRef:
        key: service-wallet-address-mainnet
