apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kargo-git-credentials
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: kargo-git-credentials
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git  # Kargo discovers credentials via this label
      data:
        repoURL: "https://github.com/amoghjay/k8s-chaos-promotion.git"
        username: "amoghjay"
        password: "{{ .githubPat }}"
  data:
    - secretKey: githubPat
      remoteRef:
        key: github-pat
