apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: url-shortener
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: url-shortener
      sources:
        direct: true  # gets freight directly from Warehouse (not from another stage)

  promotionTemplate:
    spec:
      vars:
        - name: repoURL
          value: https://github.com/amoghjay/k8s-chaos-promotion.git

      steps:
        - task:
            name: promote-dev  # references our PromotionTask
          vars:
            - name: repoURL
              value: ${{ vars.repoURL }}

  # After promotion, verify the app is healthy before marking freight as verified
  # Staging will only receive freight that passed this check
  verification:
    analysisTemplates:
      - name: health-check
    args:
      - name: service-url
        value: http://url-shortener-dev.url-shortener-dev.svc.cluster.local:80
