#!/usr/bin/env bash
# Phase 06 — GitOps + Kargo orchestration
#
# CRITICAL ORDERING (encoded from migration gotcha #4):
#   ApplicationSet MUST be applied BEFORE Kargo Warehouse.
#   Otherwise Stage step-6 (argocd-update) fails with:
#     "unable to find Argo CD Application 'url-shortener-dev' in namespace 'argocd'"
#   and the failed Promotion needs manual recovery.
#
# Sequence:
#   1. Apply root-app (spawns observability + chaos-jobs)
#   2. Wait for monitoring ns to exist (root-app creates it)
#   3. Apply Grafana ExternalSecret (deferred from Phase 05)
#   4. Apply Kargo Project + ProjectConfig + credentials-git + AnalysisTemplate + 3 Stages
#   5. Apply ApplicationSet (creates url-shortener-{dev,staging,prod} ArgoCD apps)  ← BEFORE warehouse
#   6. Apply Kargo Warehouse (starts polling GAR)
#   7. Force chaos-jobs sync (was OutOfSync because url-shortener-staging ns didn't exist on first try)

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

log_step "Phase 06 — GitOps + Kargo (with safe ordering)"

K8S_DIR="$REPO_ROOT/kubernetes"

# --- 1. root-app ---
log_info "Applying root-app (ArgoCD App-of-Apps)"
k8s_apply "$K8S_DIR/argocd/root-app.yaml"

if [ "$DRY_RUN" != "true" ]; then
  wait_for "monitoring namespace created by root-app" \
    "kubectl get ns monitoring >/dev/null 2>&1" \
    180
fi

# --- 2. Grafana ExternalSecret (now that monitoring ns exists) ---
log_info "Applying Grafana ExternalSecret (deferred from Phase 05)"
k8s_apply "$K8S_DIR/bootstrap/secrets/external-secrets-monitoring.yaml"

if [ "$DRY_RUN" != "true" ]; then
  wait_for "grafana-admin-secret created by ESO" \
    "kubectl get secret grafana-admin-secret -n monitoring >/dev/null 2>&1" \
    60

  # Kick Grafana pod if it's stuck on missing secret (idempotent — no-op if Running)
  if kubectl get pods -n monitoring -l app.kubernetes.io/name=grafana -o jsonpath='{.items[*].status.phase}' 2>/dev/null | grep -q Pending; then
    log_info "Bouncing Grafana pod to pick up newly-created secret"
    run kubectl delete pod -n monitoring -l app.kubernetes.io/name=grafana --ignore-not-found=true
  fi
fi

# --- 3. Kargo resources (project first — creates url-shortener ns) ---
log_info "Applying Kargo resources (excluding warehouse for now)"
k8s_apply "$K8S_DIR/kargo/project.yaml"
k8s_apply "$K8S_DIR/kargo/projectconfig.yaml"
k8s_apply "$K8S_DIR/kargo/credentials-git.yaml"
k8s_apply "$K8S_DIR/kargo/analysistemplate.yaml"
k8s_apply "$K8S_DIR/kargo/stage-dev.yaml"
k8s_apply "$K8S_DIR/kargo/stage-staging.yaml"
k8s_apply "$K8S_DIR/kargo/stage-prod.yaml"

if [ "$DRY_RUN" != "true" ]; then
  wait_for "Kargo credentials-git secret synced by ESO" \
    "kubectl get secret kargo-git-credentials -n url-shortener >/dev/null 2>&1" \
    60
fi

# --- 4. ApplicationSet — BEFORE Warehouse (gotcha #4) ---
log_info "Applying ApplicationSet (must precede Warehouse — see migration gotcha #4)"
k8s_apply "$K8S_DIR/apps/applicationset.yaml"

if [ "$DRY_RUN" != "true" ]; then
  wait_for "url-shortener-dev ArgoCD Application generated" \
    "kubectl get app url-shortener-dev -n argocd >/dev/null 2>&1" \
    60
  log_ok "All 3 url-shortener Applications generated by ApplicationSet"
fi

# --- 5. Warehouse (last — now starts polling, destinations exist) ---
log_info "Applying Kargo Warehouse"
k8s_apply "$K8S_DIR/kargo/warehouse.yaml"

# --- 6. Force chaos-jobs sync (its target ns may have been missing on first sync attempt) ---
if [ "$DRY_RUN" != "true" ]; then
  if kubectl get app chaos-jobs -n argocd >/dev/null 2>&1; then
    SYNC_STATUS=$(kubectl get app chaos-jobs -n argocd -o jsonpath='{.status.sync.status}' 2>/dev/null)
    if [ "$SYNC_STATUS" != "Synced" ]; then
      log_info "Forcing chaos-jobs sync (was: $SYNC_STATUS)"
      kubectl patch app chaos-jobs -n argocd --type merge -p '{"operation":{"sync":{}}}'
    fi
  else
    log_warn "chaos-jobs ArgoCD app not yet visible; root-app may still be reconciling"
  fi
fi

log_ok "Phase 06 complete"
log_info "Note: dev stage will auto-promote once Warehouse finds a Freight."
log_info "      staging/prod are manual gates — promote via Kargo UI when ready."
