{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "url-shortener.fullname" . }}-external-secret
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "url-shortener.fullname" . }}-secret
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: "postgresql://{{ .Values.postgresql.auth.username }}:{{ "{{" }} .database_password {{ "}}" }}@{{ include "url-shortener.postgresHost" . }}:5432/{{ .Values.postgresql.auth.database }}"
        RADIUS_RPC_URL: "{{ "{{" }} .radius_rpc_url {{ "}}" }}"
        SERVICE_WALLET_ADDRESS: "{{ "{{" }} .service_wallet_address {{ "}}" }}"
  data:
    - secretKey: database_password
      remoteRef:
        key: database-password
    - secretKey: radius_rpc_url
      remoteRef:
        key: {{ .Values.externalSecrets.radiusRpcUrlSecret }}
    - secretKey: service_wallet_address
      remoteRef:
        key: {{ .Values.externalSecrets.serviceWalletSecret }}
{{- end }}
